#!/usr/bin/env ruby

require 'fileutils'

browser = ENV['BROWSER'] ? ENV['BROWSER'] : 'xdg-open'
clipcmd = "echo -n %s | xclip -selection clipboard"

scheme = '%Y-%m-%d-%s.png'
location = "#{ENV['HOME']}/images/"
abort("set location to your liking. #{location} not found.") \
  unless Dir.exist?(location)

proxy_url = ENV['http_proxy'] ? ENV['http_proxy'] : ''
# proxy example: http://<user>:<password>@<ipaddr>:<port>

idfile = "#{ENV['HOME']}/.gyazo.id"
idbak = idfile + Time.new.strftime("_%Y%m%d%H%M%S.bak")
id = File.exist?(idfile) ? File.read(idfile).chomp : ''

if ARGV.size > 0
  abort("#{ARGV[0]} not found") unless File.exist?(ARGV[0])
  create_path = proc { "#{location}#{Time.now.strftime(scheme)}".gsub!(/\.png$/, File.extname(ARGV[0])) }
  while File.exist?(path = create_path.call())
    sleep 1
  end
  FileUtils.cp(ARGV[0], path)
else
  path = `scrot -s '#{scheme}' -e 'mv $f #{location}$f; echo -n #{location}$f'`
  abort("Did not capture screenshot") unless path != ""
end

# upload to gyazo website
curl = "curl -i -s -X POST gyazo.com/upload.cgi "\
        "-F 'id=#{id}' " \
        "-F 'imagedata=@#{path}' " \
        "-F 'filename=gyazo.com' " \
        "-x #{proxy_url.empty? ? "''" : proxy_url}"

data = `#{curl}`

data.split("\r\n").each do | header_str |
  header_arr = header_str.split(": ")
  next if header_arr[0] != "X-Gyazo-Id" # next if not X-Gyazo-Id
  
  newid = header_arr[1]
  break if newid == "" # break if no id

  Dir.mkdir(File.dirname(idfile)) if !File.exist?(File.dirname(idfile))
  File.rename(idfile, idbak) if File.exist?(idfile)
  File.open(idfile, 'w') { | f | f.write(newid) }
end

# copy to clipboard and open in browser
system %(#{clipcmd % [data.split("\r\n\r\n")[-1]]})
system %(#{browser} '#{data.split("\r\n\r\n")[-1]}' >/dev/null 2>&1)